# This is a basic workflow to help you get started with Actions

name: pro invest CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
     runs-on: ubuntu-latest
     steps:
      - name: Run Android Lint Checker
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Generate Gradle checksums
        run: |
          find buildSrc -name "*.kt" -type f | sort | xargs shasum  > gradle-checksums.txt
          cat gradle-checksums.txt
      - uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('gradle-checksums.txt') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ hashFiles('gradle-checksums.txt') }}-
            
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: lintDebug
        run: ./gradlew lint

      - uses: actions/upload-artifact@v2
        with:
          name: android-lint-report
          path: ./**/build/reports/lint-results.xml
     
  # This workflow contains a single job called "ktlint"
  ktlint:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       # Runs a set of commands using the runners shell
       - name: "checkout"
         uses: actions/checkout@v2
       # Runs a set of commands using the runners shell
       - name: "ktlint"
         uses: "vroy/gha-kotlin-linter@v1"
     
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
